apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Desarrollo sobre Kubernetes con Helm</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                background-color: #f4f4f9;
            }
            h1, h2 {
                color: #2c3e50;
            }
            ul {
                list-style-type: square;
            }
            .container {
                max-width: 800px;
                margin: 0 auto;
                background: #fff;
                padding: 20px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Desarrollo sobre Kubernetes con Helm</h1>
            <p>Este curso avanzado está diseñado para desarrolladores y especialistas en DevOps interesados en desplegar y gestionar aplicaciones modernas en Kubernetes utilizando Helm.</p>
            <h2>Temas del Curso</h2>
            <ul>
                <li>Repaso de Kubernetes</li>
                <li>Introducción a Helm</li>
                <li>Despliegue de aplicaciones</li>
                <li>Administración fundamental de contenedores</li>
                <li>Monitoreo de Kubernetes</li>
                <li>Uso de herramientas de Helm y ArgoCD</li>
                <li>Seguridad en Kubernetes</li>
                <li>Despliegue y escalado de microservicios</li>
                <li>Almacenamiento y persistencia de datos</li>
                <li>Integración de Kubernetes con herramientas DevOps</li>
                <li>Prácticas avanzadas en desarrollo con Kubernetes</li>
                <li>Proyecto final: Aplicación completa en Kubernetes con Helm</li>
            </ul>
            <h2>Requisitos</h2>
            <ul>
                <li>Conocimientos previos en Spring, React, microservicios, Docker y Kubernetes</li>
                <li>Equipo con Linux o WSL</li>
                <li>Instalación de Minikube, Docker, Helm, Prometheus y Grafana</li>
            </ul>
        </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-init
  namespace: default
  labels:
    app: nginx-with-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-with-init
  template:
    metadata:
      labels:
        app: nginx-with-init
    spec:
      volumes:
      - name: html-config
        configMap:
          name: html-config
      - name: nginx-html
        emptyDir: {}
      initContainers:
      - name: init-container
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
          - cp /config/index.html /usr/share/nginx/html/index.html;
        volumeMounts:
        - name: html-config
          mountPath: /config
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
