---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny
  namespace: databases
spec:
  podSelector: {}  # Apply to all pods in the namespace
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          environment: production
---
