apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-limits
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "1"
    limits.memory: "1Gi"
---
