apiVersion: batch/v1
kind: Job
metadata:
  name: time-job
  namespace: istio-apps
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: time-container
        image: busybox
        command: ["sh", "-c", "date; sleep 10"]
      restartPolicy: Never