apiVersion: v1
entries:
  curso-apps:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-11-22T20:04:56.183990531+01:00"
    description: Este chart esta dedicado a la administracion de la app react
    digest: 9f68c8ceb3dd308ad0bcc16ea727d415e44b1287d5994b1deb6538c93492875c
    name: curso-apps
    type: application
    urls:
    - https://rafaeltovargarrido.github.io/k8s/charts/curso-apps-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-11-22T20:04:56.183784425+01:00"
    description: Este chart esta dedicado a la administracion de la app react
    digest: 372b94524cf003d85a3d62f50c7b72e8eb5634b484124f8d27076eb8c3bd3bdb
    name: curso-apps
    type: application
    urls:
    - https://rafaeltovargarrido.github.io/k8s/charts/curso-apps-0.0.1.tgz
    version: 0.0.1
generated: "2024-11-22T20:04:56.18348059+01:00"
