apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: react
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       apps-curso-apps
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "curso-apps"
      minAllowed:
        cpu: "10m"
        memory: "32Mi"
      maxAllowed:
        cpu: "100m"
        memory: "256Mi"