apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: react
  namespace: prod
spec:
  scaleTargetRef:
    name: apps-curso-apps
  maxReplicaCount: 10    
  minReplicaCount: 1
  triggers:
  - type: cron
    metadata:
      # Required
      timezone: Europe/Madrid
      start: 0 6 * * 1-5        # At 6:00 AM
      end: 0 20 * * 1-5         # At 8:00 PM
      desiredReplicas: "2"
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.istio-system:9090
      threshold: '2'
      query: sum(rate(istio_requests_total{destination_service_name="apps-curso-apps", response_code="200"}[1m]))            
  - type: cpu
    metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    metadata:
      value: "75"            