apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-app.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "react-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: TCP
      name: http
  selector:
    {{- include "react-app.selectorLabels" . | nindent 4 }}
