apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: default
spec:
  project: default
  sources:
    - chart: redis
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 20.3.0
      helm:
        releaseName: redis
        parameters:
        - name: "auth.existingSecret"
          value: prod-redis-secret      
        #values: |
        #  auth:
        #    existingSecret: prod-redis-secret      
    - repoURL: https://github.com/rafaeltovargarrido/k8s
      path: argocd/apps/k8s/
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default