apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: test-1
  labels:
    app: httpbin
    version: httpbin-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          args: ["gunicorn", "-b", "0.0.0.0:80", "httpbin:app", "--log-level", "debug"]          
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: test-1
  labels:
    app: httpbin
spec:
  type: ClusterIP
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: prod-redis-secret
  namespace: test-1
type: Opaque
data:
  redis-password: Y3Vyc28K
      