apiVersion: v1
kind: Pod
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  containers:
    - name: httpbin
      image: kennethreitz/httpbin
      args: ["gunicorn", "-b", "0.0.0.0:80", "httpbin:app", "--log-level", "debug"]
      ports:
        - containerPort: 80