apiVersion: v1
kind: Pod
metadata:
  name: httpbin
  namespace: test-1
  labels:
    app: httpbin
    version: v1
spec:
  containers:
    - name: httpbin
      image: kennethreitz/httpbin
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-1
  labels:
    app: nginx
    version: v1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
