name: Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}      
      - name: Build the Docker image
        run: docker build . -t ghcr.io/${{ github.actor }}/k8s:latest
      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.actor }}/k8s:latest
      - name: Build and push React image
        uses: docker/build-push-action@v6
        with:
          context: ./react-app/
          push: true
          tags: ghcr.io/${{ github.actor }}/react:latest
      - name: Build and push Sprint image
        uses: docker/build-push-action@v6
        with:
          context: ./sprint-app
          push: true
          tags: ghcr.io/${{ github.actor }}/react:latest          