name: Docker Image

on: push

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PAT }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          packages_with_index: true
          pages_branch: main
        env:
          CR_TOKEN: "${{ secrets.GH_PAT }}"  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}      
      - name: Build and push React image
        uses: docker/build-push-action@v6
        with:
          context: ./react-app/
          push: true
          tags: ghcr.io/${{ github.actor }}/react:latest
      - name: Build and push Sprint image
        uses: docker/build-push-action@v6
        with:
          context: ./sprint-app
          push: true
          tags: ghcr.io/${{ github.actor }}/sprint:latest          
      - name: Build and push Python image
        uses: docker/build-push-action@v6
        with:
          context: ./python-app
          push: true
          tags: ghcr.io/${{ github.actor }}/python:latest                    
  
  validar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }} 
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'nginx:1.16'
          format: 'table'  
          cache-dir: './trivy-cache'
